### ISSUE TITLE
nilerr: internal error: nil Pkg importing "github.com/onsi/gomega/types" from "github.com/onsi/gomega/internal/assertion"

### ISSUE THREAD

**Issue by advancedwebdeveloper** [cybozu-go/sabakan#197] opened 2020-10-18 15:34 UTC
Hi.

Caught such an error:
> $ make
> test -z "$(gofmt -s -l . | grep -v '^vendor' | tee /dev/stderr)"
> test -z "$(golint $(go list ./... | grep -v /vendor/) | grep -v '/mtest/.*: should not use dot imports' | tee /dev/stderr)"
> test -z "$(nilerr ./... 2>&1 | tee /dev/stderr)"
> nilerr: internal error: nil Pkg importing "github.com/onsi/gomega/types" from "github.com/onsi/gomega/internal/assertion"
> make: *** [Makefile:26: test] Error 1

> $ go version
> go version go1.15.2 gollvm LLVM 12.0.0git linux/amd64
>

> $ go env
> GO111MODULE=""
> GOARCH="amd64"
> GOBIN=""
> GOCACHE="/home/oceanfish81/.cache/go-build"
> GOENV="/home/oceanfish81/.config/go/env"
> GOEXE=""
> GOFLAGS=""
> GOHOSTARCH="amd64"
> GOHOSTOS="linux"
> GOINSECURE=""
> GOMODCACHE="/home/oceanfish81/go/pkg/mod"
> GONOPROXY=""
> GONOSUMDB=""
> GOOS="linux"
> GOPATH="/home/oceanfish81/go"
> GOPRIVATE=""
> GOPROXY="https://proxy.golang.org,direct"
> GOROOT="/home/oceanfish81/gollvm_dist"
> GOSUMDB="sum.golang.org"
> GOTMPDIR=""
> GOTOOLDIR="/home/oceanfish81/gollvm_dist/tools"
> GCCGO="/home/oceanfish81/gollvm_dist/bin/llvm-goc"
> AR="ar"
> CC="/usr/bin/clang"
> CXX="/usr/bin/clang++"
> CGO_ENABLED="1"
> GOMOD="/home/oceanfish81/sabakan/go.mod"
> CGO_CFLAGS="-g -O2"
> CGO_CPPFLAGS=""
> CGO_CXXFLAGS="-g -O2"
> CGO_FFLAGS="-g -O2"
> CGO_LDFLAGS="-g -O2"
> PKG_CONFIG="pkg-config"
> GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build032338975=/tmp/go-build -gno-record-gcc-switches -funwind-tables"
> 

CC @tenntenn

**Comment by masa213f** [comment] 2020-10-19 08:34
Thanks for the report. I will update this issue soon.

FYI:
nilerr v0.0.1 doesn't cause an error, so if you're in a hurry, try downgrading your environment's nilerr and running it.

**Comment by masa213f** [comment] 2020-10-19 08:36
@advancedwebdeveloper 
Thanks for the report. I will update this issue soon.

FYI:
nilerr v0.0.1 doesn't cause an error, so if you're in a hurry, try downgrading your environment's nilerr and running it.

**Comment by masa213f** [comment] 2020-10-20 07:12
@advancedwebdeveloper 
Hi, the above comment was wrong.
The error is probably caused by building [`golang.org/x/tools v0.0.0-20190307163923-6a08e3108db3`](https://github.com/gostaticanalysis/nilerr/blob/v0.1.0/go.mod#L7) with go 1.15.

Could you try to update the `nilerr` in your environment with the following command and run it?
```
$ go get github.com/gostaticanalysis/nilerr/cmd/nilerr
or 
$ cd <path to nilerr source>
$ go get -u
$ go build ./cmd/nilerr
```

**Comment by advancedwebdeveloper** [comment] 2020-10-20 08:57
Sure thing, will try to do this today.

**Comment by advancedwebdeveloper** [comment] 2020-10-20 08:58
> @advancedwebdeveloper
> Hi, the above comment was wrong.
> The error is probably caused by building [`golang.org/x/tools v0.0.0-20190307163923-6a08e3108db3`](https://github.com/gostaticanalysis/nilerr/blob/v0.1.0/go.mod#L7) with go 1.15.
> 
> Could you try to update the `nilerr` in your environment with the following command and run it?
> 
> ```
> $ go get github.com/gostaticanalysis/nilerr/cmd/nilerr
> or 
> $ cd <path to nilerr source>
> $ go get -u
> $ go build ./cmd/nilerr
> ```


@ianlancetaylor ,

**Comment by advancedwebdeveloper** [comment] 2020-10-20 08:59
> > @advancedwebdeveloper
> > Hi, the above comment was wrong.
> > The error is probably caused by building [`golang.org/x/tools v0.0.0-20190307163923-6a08e3108db3`](https://github.com/gostaticanalysis/nilerr/blob/v0.1.0/go.mod#L7) with go 1.15.

@ianlancetaylor,
any comments?

> > Could you try to update the `nilerr` in your environment with the following command and run it?
> > ```
> > $ go get github.com/gostaticanalysis/nilerr/cmd/nilerr
> > or 
> > $ cd <path to nilerr source>
> > $ go get -u
> > $ go build ./cmd/nilerr

**Comment by ianlancetaylor** [comment] 2020-10-20 19:39
@advancedwebdeveloper I'm sorry, I don't understand what you are asking me to comment on.

**Comment by advancedwebdeveloper** [comment] 2020-10-20 21:56
I am asking whether you see what is the problem around golang.org/x/tools v0.0.0-20190307163923-6a08e3108db3

**Comment by ianlancetaylor** [comment] 2020-10-20 23:43
Is the problem fixed by a newer version of golang.org/x/tools?  If so, does it matter why the earlier version failed?

**Comment by ysksuzuki** [comment] 2020-10-20 23:54
@advancedwebdeveloper @ianlancetaylor 
The issue https://github.com/golang/go/issues/33554 is present with the version of golang.org/x/tools nilerr depends on, but the issue has been fixed with a newer version. So upgrading golang.org/x/tools will fix it.

**Comment by masa213f** [comment] 2020-10-26 00:38
I threw a PR to nilerr. https://github.com/gostaticanalysis/nilerr/pull/6
There is no problem with sabakan, so I will close this issue.

**Closed by masa213f** 2020-10-26 00:38 UTC
Labels: bug
